name = "tasks-app"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-09"

[[d1_databases]]
binding = "DB"
database_name = "tasks-db"
database_id = "eb8f3e6d-aafa-46a2-b8af-0bc3272c2986" # Bạn sẽ thay ID này sau khi tạo DB trên Cloudflare
